version: "3"
services:  
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    working_dir: /var/www
    networks:
      - default
    volumes:
      - .:/var/www
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - default    